### ISSUE TITLE
error when trying to start a new agent dinamically with ecs

### ISSUE THREAD

**Issue by willerpp** [aws-samples/serverless-jenkins-on-aws-fargate#27]
Hi guys, after deployed the solution, I was able to login in jenkins and start the first build but then nothing happens and I go this error when jenkins is trying to create a new agent task : 
and it will continue printing this in the logs in a cycle:

Asked to provision 1 agent(s) for: simple-job-non-critical-task-2-3vc7s
Nov 22, 2022 10:56:08 PM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud provision
Will provision fargate-cloud-spot-simple-job-non-critical-task-2-3vc7s-n60qm, for label: simple-job-non-critical-task-2-3vc7s
Nov 22, 2022 10:56:08 PM SEVERE hudson.triggers.SafeTimerTask run
Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@2bf71d2 failed
java.lang.IllegalArgumentException
	at hudson.slaves.NodeProvisioner$PlannedNode.<init>(NodeProvisioner.java:102)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.provision(ECSCloud.java:283)
	at com.cloudbees.jenkins.plugins.amazonecs.ECSProvisioningStrategy.apply(ECSProvisioningStrategy.java:65)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:325)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:94)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Any clue??

**Comment by kmurray2bee** [comment]
check out the thread at https://github.com/jenkinsci/amazon-ecs-plugin/issues/291

**Comment by apogorielov** [comment]
Hi! 
I have updated configuration and ecs plugin version to address the https://github.com/jenkinsci/amazon-ecs-plugin/issues/291 topic.
Please try out the latest update available in the main branch.

Kind regards,
Alex
